### PR TITLE
Make repo::nodesource::apt compatible with puppetlabs-apt 2.x only

### PR DESCRIPTION
**Pull request by juniorsysadmin**
An equivalent PR for this has already been started in #129 - this PR just adds some more bits and pieces. It is probably preferred that this get merged AFTER the next release (see #126 )

### CODE REVIEW

**Comment by juniorsysadmin** [comment]
The tests are failing with STRICT_VARIABLES=yes, possibly due to the ::puppetversion fact in the puppetlabs-apt

**Comment by juniorsysadmin** [comment]
Rebased. TravisCI checks seem to all be okay now.

**Comment by juniorsysadmin** [comment]
@jmcclell RSpec test descriptions have now been fixed

**Comment by jmcclell** [comment]
:+1:

**Pull request merged**
