### PR TITLE
Remove soft dependency on treydock/gpg_key

### PR DESCRIPTION
**Pull request by juniorsysadmin**
Remove soft dependency on treydock/gpg_key

### CODE REVIEW

**Comment by juniorsysadmin** [comment]
Needs to be verified before merging.

**Comment by igalic** [comment]
do we not have acceptance tests for that :P

**Comment by tsde** [comment]
Just tested your changes on centos 6 and 7 flawlessly. Would be great to see this PR merged ;)

**Comment by igalic** [comment]
we'll just merge it, and let it sort out :P

**Pull request merged**
