### PR TITLE
Exodusftw qualify global config var

### PR DESCRIPTION
**Pull request by exodusftw**
modified behavior of global_config_entry type by including "onlyif" attribute on exec to ensure config variables are only added/removed when set to absent or whenever present value doesn't match desired value

### CODE REVIEW

**Comment by juniorsysadmin** [comment]
Just a few things:
- It's better if you add --global as part of ${command} to avoid confusion
- Use ${npm_path} rather than putting the whole path
..which leads to...
- Windows support. I attempted to support Windows in npm.pp with the use of alternatives for grep. I'm not sure if there is a Windows alternative to `tr` though. If you can't come up with changes that might allow this defined type to work on Windows, please put a comment in the appropriate section of the README and perhaps a code comment as well

**Comment by exodusftw** [comment]
I worked through some issues on the windows onlyif components and it should now work as expected to be idempotent and not run the global config exec when not required.

I also ensured that the `${npm_path}` variable and and `--global` entries were added.

Please review.

**Comment by juniorsysadmin** [comment]
If you do: ```$cmd_exe_path = $nodejs::cmd_exe_path,``` in the defined type, then you've already got the full path of cmd and can avoid the provider in the exec. I'm not sure if that can make things less ugly though. Anyhow, if you've tested on a Windows machine and am happy with this, just squash the commits and we'll merge it.

**Comment by igalic** [comment]
@exodusftw i think this will beed a proper [rebase](http://git-scm.com/book/en/Git-Branching-Rebasing)
@juniorsysadmin is this now addressing all of your concerns?

**Comment by juniorsysadmin** [comment]
Okay with merging after a rebase, but would prefer the use of ```$cmd_exe_path``` to slightly simplify things though. I know, I know, it should be a provider....

**Comment by exodusftw** [comment]
I will update to use the cmd path var later this evening.


Sent by Outlook for Android





On Tue, Sep 22, 2015 at 5:08 AM -0700, "Ben S" <notifications@github.com> wrote:
Okay with merging after a rebase, but would prefer the use of ```$cmd_exe_path``` to slightly simplify things though. I know, I know, it should be a provider....

---

**Comment by exodusftw** [comment]
Updated to use `$cmd_exe_path` - please review

**Comment by igalic** [comment]
this looks quite good now, @exodusftw
would you mind doing a [squash](http://www.git-scm.com/book/en/Git-Tools-Rewriting-History#Squashing-Commits) ?

**Comment by exodusftw** [comment]
Had some weirdness on the squash - but it should be sorted out - let me know if you want anymore cleanup.

**Comment by juniorsysadmin** [comment]
:+1:

**Comment by igalic** [comment]
@exodusftw rebased without the merge commit for you :)
thank you very much!

**Pull request closed without merging**
